services:
    heavy.admin.service:
        class: AppBundle\Admin\ServiceAdmin
        arguments: [~, AppBundle\Entity\Service, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Administration, label: Service }

    heavy.admin.booking:
            class: AppBundle\Admin\ReservationAdmin
            arguments: [~, AppBundle\Entity\Reservation, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: Administration, label: Reservation, label_catalogue: "AppBundle" }
            calls:
                - [ setTranslationDomain, [AppBundle]]

    heavy.admin.agency:
        class: AppBundle\Admin\AgencyAdmin
        arguments: [~, AppBundle\Entity\Agency, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Administration, label: Agency}

    heavy.admin.car:
        class: AppBundle\Admin\CarAdmin
        arguments: [~, AppBundle\Entity\Car, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des véhicules, label: Car}

    heavy.admin.client:
        class: AppBundle\Admin\ClientAdmin
        arguments: [~, AppBundle\Entity\Client, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Administration, label: Client}

    heavy.admin.reservation_created:
        class: AppBundle\Admin\ReservationCreatedAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Custom, label: Reservation Created }
        arguments: [~, ~,  AppBundle\Controller\Backend\ReservationCreatedController]
        public: true