services:
    heavy.manager.car:
        class: AppBundle\Manager\CarManager
        arguments:
            - '@doctrine'

    heavy.manager.reservation:
        class: AppBundle\Manager\ReservationManager
        arguments:
            - '@doctrine'

    heavy.manager.booking_guest:
        class: AppBundle\Manager\BookingGuestManager
        arguments:
            - '@doctrine'

    tlconseil.systempay:
            class: AppBundle\Manager\SystemPayManager
            arguments: ['@doctrine.orm.entity_manager', '@service_container']

