# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
imports:
    - { resource: managers.yml }

services:
    twig.extension.app_extension:
        class: AppBundle\Twig\AppExtension
        tags:
            - { name : twig.extension }
        arguments:
            - '@doctrine'

    twig.extension.sha_extension:
        class: AppBundle\Twig\ShaExtension
        tags:
            - { name : twig.extension }

    tlconseil.systempay.twig_extension:
        class: AppBundle\Twig\TwigExtension
        tags:
            - { name: twig.extension }

    app.services.google_cloud:
        class: AppBundle\Controller\API\GoogleCloud
        arguments: ["%cloud_storage%"]