AppBundle\Entity\Agency:
    type: entity
    table: agency
    indexes:
        FK_773DE69D4D42DB2D:
            columns:
                - pick_up_agency_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        siret:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        tvaNumber:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: tva_number
        billingAddress:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: billing_address
        billingZipCode:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: billing_zip_code
        billingCity:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: billing_city
        billingCountry:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: billing_country
        enabled:
            type: boolean
            nullable: false
    manyToOne:
        pickUpAgency:
            targetEntity: PickUpCenter
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pick_up_agency_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
