AppBundle\Entity\Car:
    type: entity
    table: car
    indexes:
        FK_773DE69D4D42DB1D:
            columns:
                - pick_up_origin_id
    uniqueConstraints:
        UNIQ_773DE69DD17F50A6:
            columns:
                - uuid
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uuid:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        registration:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        firstRegistrationAt:
            type: datetime
            nullable: true
            column: first_registration_at
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        pickUpStatus:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: pick_up_status
        pickUpDoneAt:
            type: datetime
            nullable: true
            column: pick_up_done_at
        vehicleType:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: vehicle_type
        vehicleEnergyType:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: vehicle_energy_type
        vehicleMaker:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vehicle_maker
        vehicleCnit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vehicle_cnit
        vehicleModel:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vehicle_model
        vehicleModelVariant:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vehicle_model_variant
        vehicleEngine:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: vehicle_engine
        firstHand:
            type: boolean
            nullable: false
            column: first_hand
        duplicateKeys:
            type: boolean
            nullable: false
            column: duplicate_keys
        interiorColor:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: interior_color
        exteriorColor:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: exterior_color
        passengerCapacity:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: passenger_capacity
        doors:
            type: integer
            nullable: true
            options:
                unsigned: false
        transmission:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        mileageReal:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: mileage_real
        mileageEstimate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: mileage_estimate
        lastMaintenanceMileage:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: last_maintenance_mileage
        chassisJig:
            type: boolean
            nullable: false
            column: chassis_jig
        repainted:
            type: boolean
            nullable: false
        options:
            type: json_array
            nullable: true
            length: null
            options:
                fixed: false
        pictures:
            type: json_array
            nullable: true
            length: null
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        comments:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        enabled:
            type: boolean
            nullable: false
    manyToOne:
        pickUpOrigin:
            targetEntity: PickUpCenter
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pick_up_origin_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
