AppBundle\Entity\Databasechangelog:
    type: entity
    table: DATABASECHANGELOG
    id:
        id:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        author:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: AUTHOR
        filename:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: FILENAME
        dateexecuted:
            type: datetime
            nullable: false
            column: DATEEXECUTED
        orderexecuted:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: ORDEREXECUTED
        exectype:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: EXECTYPE
        md5sum:
            type: string
            nullable: true
            length: 35
            options:
                fixed: false
            column: MD5SUM
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: DESCRIPTION
        comments:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: COMMENTS
        tag:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: TAG
        liquibase:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: LIQUIBASE
        contexts:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: CONTEXTS
        labels:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: LABELS
        deploymentId:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: DEPLOYMENT_ID
    lifecycleCallbacks: {  }
