AppBundle\Entity\Databasechangeloglock:
    type: entity
    table: DATABASECHANGELOGLOCK
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        locked:
            type: boolean
            nullable: false
            column: LOCKED
        lockgranted:
            type: datetime
            nullable: true
            column: LOCKGRANTED
        lockedby:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: LOCKEDBY
    lifecycleCallbacks: {  }
