AppBundle\Entity\Partnair:
    type: entity
    table: partnair
    indexes:
        FK_773DE69D4D42DB3D:
            columns:
                - agency_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        address:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        zipCode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: zip_code
        city:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        fullName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: full_name
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        phone:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        enabled:
            type: boolean
            nullable: false
    manyToOne:
        agency:
            targetEntity: Agency
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                agency_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
