AppBundle\Entity\PickUpCenter:
    type: entity
    table: pick_up_center
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        address:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        zipCode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: zip_code
        city:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        fullName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: full_name
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        phone:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        openingHours:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
            column: opening_hours
        enabled:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
