AppBundle\Entity\Price:
    type: entity
    table: price
    indexes:
        FK_773DE69D4D42DB5D:
            columns:
                - service_id
        FK_773DE69D4D42DB6D:
            columns:
                - car_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        toPay:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            column: to_pay
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        service:
            targetEntity: Service
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                service_id:
                    referencedColumnName: id
            orphanRemoval: false
        car:
            targetEntity: Car
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                car_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
