AppBundle\Entity\Service:
    type: entity
    table: service
    indexes:
        FK_773DE69D4D42DB4D:
            columns:
                - agency_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        enabled:
            type: boolean
            nullable: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        description:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        agency:
            targetEntity: Agency
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                agency_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
