<?php
/**
 * Created by PhpStorm.
 * User: ashley
 * Date: 27/03/18
 * Time: 16:33
 */

namespace AppBundle\Admin;


use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Route\RouteCollection;

class ReservationListAdmin extends AbstractAdmin
{
    protected $baseRoutePattern = "list_booking_created";
    protected $baseRouteName = "list_booking_created";

    protected function configureRoutes(RouteCollection $collection)
    {
        /*parent::configureRoutes($collection); // TODO: Change the autogenerated stub
        $collection->clearExcept(['list']);*/
    }

}